name: lefine_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  flutter_svg: ^1.1.6
  auto_route: ^5.0.4
  very_good_analysis: ^3.1.0
  kartal: ^2.8.0
  flutter_gen:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/
    - assets/images/background.jfif

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
